### ISSUE TITLE
See typing and corpus on  same line

### ISSUE THREAD

**Issue by iltimasd** [cslarsen/wpm#35]
Would love to make a version that shows what you're typing on top of what needs to be typed. For me it reflects text area writing where you see your inputs live. maybe it just looks like you overwriting in red when youve mad a mistake

I'd actually love to try my hand at this if you could point me in the right direction.

**Comment by cslarsen** [comment]
I agree, and I've been thinking the same, but not found a good solution.

Take a look at `highlight_progress` in `screen.py`. There, `incorrect` is the number of incorrectly typed characters from the current position. I think what the user actually types is in `self._edit` somewhere (maybe in the `game.py` file). I believe it should be quite easy: Instead of just highlighting in red, take the characters from this `_edit` buffer instead.

Lastly, when the user backspaces, you need to render the correct words again. Right now, I just change the background color, because I don't overwrite. Should be easy to fix. I think I operate on one character at a time, because it creates less latency for screen updates.

**Comment by cslarsen** [comment]
This issue is more than a year old. Closing.
